language: python
python: 3.7

addons:
  apt:
    update: true
    packages:
      - xvfb

services:
  - xvfb

# To turn off cached cython files and compiler cache
# set NOCACHE-true
# To delete caches go to https://travis-ci.org/OWNER/REPOSITORY/caches or run
# travis cache --delete inside the project directory from the travis command line client
# The cache directories will be deleted if anything in ci/ changes in a commit
cache:
  apt: true
  ccache: true
  directories:
    - $HOME/.cache # cython cache

env:
  global:
    # create a github personal access token
    # cd pandas-dev/pandas
    # travis encrypt 'PANDAS_GH_TOKEN=personal_access_token' -r pandas-dev/pandas
    - secure: "EkWLZhbrp/mXJOx38CHjs7BnjXafsqHtwxPQrqWy457VDFWhIY1DMnIR/lOWG+a20Qv52sCsFtiZEmMfUjf0pLGXOqurdxbYBGJ7/ikFLk9yV2rDwiArUlVM9bWFnFxHvdz9zewBH55WurrY4ShZWyV+x2dWjjceWG5VpWeI6sA="

git:
  depth: false

matrix:
  fast_finish: true

  include:
    - arch: arm64-graviton2
      virt: lxd
      group: edge
      env:
        - JOB="3.7, arm64" PYTEST_WORKERS="auto" ENV_FILE="ci/deps/travis-37-arm64.yaml" PATTERN="(not slow and not network and not clipboard and not arm_slow)"

before_install:
  - echo "before_install"
  # Use blocking IO on travis.  Ref:  https://github.com/travis-ci/travis-ci/issues/8920#issuecomment-352661024
  - python -c 'import os,sys,fcntl; flags = fcntl.fcntl(sys.stdout, fcntl.F_GETFL); fcntl.fcntl(sys.stdout, fcntl.F_SETFL, flags&~os.O_NONBLOCK);'
  - source ci/travis_process_gbq_encryption.sh
  - export PATH="$HOME/miniconda3/bin:$PATH"
  - df -h
  - pwd
  - uname -a
  - git --version
  - ./ci/check_git_tags.sh

install:
  - echo "install start"
  - ci/prep_cython_cache.sh
  - ci/setup_env.sh
  - ci/submit_cython_cache.sh
  - echo "install done"

script:
  - echo "script start"
  - echo "$JOB"
  - source activate pandas-dev
  - ci/run_tests.sh

after_script:
  - echo "after_script start"
  - source activate pandas-dev && pushd /tmp && python -c "import pandas; pandas.show_versions();" && popd
  - ci/print_skipped.py
  - echo "after_script done"
