# Local development dependencies including docs building, website upload, ASV benchmark
name: pandas-dev
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip

  # build dependencies
  - versioneer[toml]
  - cython=0.29.33
  - meson[ninja]=1.0.1
  - meson-python=0.13.1

  # test dependencies
  - pytest>=7.0.0
  - pytest-cov
  - pytest-xdist>=2.2.0
  - pytest-asyncio>=0.17.0
  - coverage

  # required dependencies
  - python-dateutil
  - numpy
  - pytz

  # optional dependencies
  - beautifulsoup4>=4.11.1
  - blosc
  - brotlipy>=0.7.0
  - bottleneck>=1.3.4
  - fastparquet>=0.8.1
  - fsspec>=2022.05.0
  - html5lib>=1.1
  - hypothesis>=6.46.1
  - gcsfs>=2022.05.0
  - ipython
  - jinja2>=3.1.2
  - lxml>=4.8.0
  - matplotlib>=3.6.1
  - numba>=0.55.2
  - numexpr>=2.8.0  # pin for "Run checks on imported code" job
  - openpyxl>=3.0.10
  - odfpy>=1.4.1
  - py
  - psycopg2>=2.9.3
  - pyarrow>=7.0.0
  - pymysql>=1.0.2
  - pyreadstat>=1.1.5
  - pytables>=3.7.0
  - python-snappy>=0.6.1
  - pyxlsb>=1.0.9
  - s3fs>=2022.05.0
  - scipy>=1.8.1
  - sqlalchemy>=1.4.36
  - tabulate>=0.8.10
  - xarray>=2022.03.0
  - xlrd>=2.0.1
  - xlsxwriter>=3.0.3
  - zstandard>=0.17.0

  # downstream packages
  - dask-core
  - seaborn-base

  # local testing dependencies
  - moto
  - flask

  # benchmarks
  - asv>=0.5.1

  ## The compiler packages are meta-packages and install the correct compiler (activation) packages on the respective platforms.
  - c-compiler
  - cxx-compiler

  # code checks
  - black=23.3.0
  - cpplint
  - flake8=6.0.0
  - isort>=5.2.1  # check that imports are in the right order
  - mypy=1.2
  - pre-commit>=2.15.0
  - pyupgrade
  - ruff=0.0.215

  # documentation
  - gitpython  # obtain contributors from git for whatsnew
  - gitdb
  - natsort  # DataFrame.sort_values doctest
  - numpydoc
  - pydata-sphinx-theme
  - pytest-cython  # doctest
  - sphinx
  - sphinx-design
  - sphinx-copybutton
  - types-python-dateutil
  - types-PyMySQL
  - types-pytz
  - types-PyYAML
  - types-setuptools

  # documentation (jupyter notebooks)
  - nbconvert>=6.4.5
  - nbsphinx
  - pandoc
  - ipywidgets
  - nbformat
  - notebook>=6.0.3
  - ipykernel

  # web
  - jinja2  # in optional dependencies, but documented here as needed
  - markdown
  - feedparser
  - pyyaml
  - requests
  - pygments # Code highlighting

  - pip:
      - sphinx-toggleprompt
      - typing_extensions; python_version<"3.11"
      - tzdata>=2022.1
