parameters:
  name: ''
  vmImage: ''

jobs:
- job: ${{ parameters.name }}
  timeoutInMinutes: 90
  pool:
    vmImage: ${{ parameters.vmImage }}
  strategy:
    matrix:
      py38:
        ENV_FILE: ci/deps/actions-38.yaml
        CONDA_PY: "38"

      py39:
        ENV_FILE: ci/deps/actions-39.yaml
        CONDA_PY: "39"

      py310:
        ENV_FILE: ci/deps/actions-310.yaml
        CONDA_PY: "310"

  steps:
    - powershell: |
        Write-Host "##vso[task.prependpath]$env:CONDA\Scripts"
        Write-Host "##vso[task.prependpath]$HOME/miniconda3/bin"
      displayName: 'Add conda to PATH'
    - script: conda update -q -n base conda
      displayName: 'Update conda'

    - bash: |
        conda env create -q --file ci\\deps\\actions-$(CONDA_PY).yaml
      displayName: 'Create anaconda environment'
    - bash: |
        source activate pandas-dev
        conda list
        python setup.py build_ext -q -j 4
        python -m pip install --no-build-isolation -e .
      displayName: 'Build'
    - bash: |
        source activate pandas-dev
        wmic.exe cpu get caption, deviceid, name, numberofcores, maxclockspeed
        ci/run_tests.sh
      displayName: 'Test'
    - task: PublishTestResults@2
      condition: succeededOrFailed()
      inputs:
        failTaskOnFailedTests: true
        testResultsFiles: 'test-data.xml'
        testRunTitle: ${{ format('{0}-$(CONDA_PY)', parameters.name) }}
      displayName: 'Publish test results'
