name: 32 Bit Linux

on:
  push:
    branches:
      - main
      - 1.4.x
  pull_request:
    branches:
      - main
      - 1.4.x
    paths-ignore:
      - "doc/**"

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Run 32-bit manylinux2014 Docker Build / Tests
        run: |
          docker pull quay.io/pypa/manylinux2014_i686
          docker run --platform linux/386 -v $(pwd):/pandas quay.io/pypa/manylinux2014_i686 \
          /bin/bash -xc "cd pandas && \
          /opt/python/cp38-cp38/bin/python -m venv ~/virtualenvs/pandas-dev && \
          . ~/virtualenvs/pandas-dev/bin/activate && \
          python -m pip install --no-deps -U pip wheel 'setuptools<60.0.0' && \
          pip install cython numpy python-dateutil pytz pytest pytest-xdist pytest-asyncio>=0.17 hypothesis && \
          python setup.py build_ext -q -j2 && \
          python -m pip install --no-build-isolation --no-use-pep517 -e . && \
          export PANDAS_CI=1 && \
          pytest -m 'not slow and not network and not clipboard and not single_cpu' pandas --junitxml=test-data.xml"

      - name: Publish test results for Python 3.8-32 bit full Linux
        uses: actions/upload-artifact@v3
        with:
          name: Test results
          path: test-data.xml
        if: failure()
