name: Windows-MacOS

on:
  push:
    branches:
      - main
      - 1.4.x
  pull_request:
    branches:
      - main
      - 1.4.x
    paths-ignore:
      - "doc/**"

env:
  PANDAS_CI: 1
  PYTEST_TARGET: pandas
  PYTEST_WORKERS: auto
  PATTERN: "not slow and not db and not network and not single_cpu"


jobs:
  pytest:
    defaults:
      run:
        shell: bash -el {0}
    timeout-minutes: 90
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
        env_file: [actions-38.yaml, actions-39.yaml, actions-310.yaml]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    name: ${{ format('{0} {1}', matrix.os, matrix.env_file) }}
    concurrency:
      # https://github.community/t/concurrecy-not-work-for-push/183068/7
      group: ${{ github.event_name == 'push' && github.run_number || github.ref }}-${{ matrix.env_file }}-${{ matrix.os }}
      cancel-in-progress: true

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Conda
      uses: ./.github/actions/setup-conda
      with:
        environment-file: ci/deps/${{ matrix.env_file }}
        pyarrow-version: ${{ matrix.os == 'macos-latest' && '6' || '' }}

    - name: Build Pandas
      uses: ./.github/actions/build_pandas

    - name: Test
      uses: ./.github/actions/run-tests
