name: Windows

on:
  push:
    branches:
      - main
      - 1.4.x
  pull_request:
    branches:
      - main
      - 1.4.x
    paths-ignore:
      - "doc/**"

env:
  PANDAS_CI: 1
  PYTEST_TARGET: pandas
  PYTEST_WORKERS: auto
  PATTERN: "not slow and not db and not network and not single_cpu"


jobs:
  pytest:
    runs-on: windows-latest
    defaults:
      run:
        shell: bash -el {0}
    timeout-minutes: 90
    strategy:
      matrix:
        env_file: [actions-38.yaml, actions-39.yaml, actions-310.yaml]
      fail-fast: false
    concurrency:
      # https://github.community/t/concurrecy-not-work-for-push/183068/7
      group: ${{ github.event_name == 'push' && github.run_number || github.ref }}-${{ matrix.env_file }}-windows
      cancel-in-progress: true

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install Dependencies
      uses: conda-incubator/setup-miniconda@v2.1.1
      with:
        mamba-version: "*"
        channels: conda-forge
        activate-environment: pandas-dev
        channel-priority: strict
        environment-file: ci/deps/${{ matrix.env_file }}
        use-only-tar-bz2: true

    - name: Build Pandas
      uses: ./.github/actions/build_pandas

    - name: Test
      run: ci/run_tests.sh

    - name: Build Version
      run: conda list

    - name: Publish test results
      uses: actions/upload-artifact@v3
      with:
        name: Test results
        path: test-data.xml
      if: failure()

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
        flags: unittests
        name: codecov-pandas
        fail_ci_if_error: false
